threads: 24
aucs:
- name: c_1tKEB-tTc28
  input_path: /home/ubuntu/auction_videos/video_imgs/1tKEB-tTc28_20th_21st Century Art Evening Sale and The Masterpiece Auction II From The Triazza Collection
  output_path:  /home/ubuntu/ocr_results/c_1tKEB-tTc28
  text_result_file: text_result.c_1tKEB-tTc28.csv
  price_result_file: price_result.c_1tKEB-tTc28.csv

  start_frame: 15
  end_frame: 244635
  step: 15
  report_interval: 1630

  extract_pattern_one_line: '(?m)^LOT\s*(\d+[A-Z_]*)\s*(.*)\s*BID\s*\|\s*(HK\$|£|€|¥|\$)(.*)'
  extract_pattern_multiple_line: '(?m)^LOT\s*(\d+[A-Z_]*)\s*(.*\n.*)\s*BID\s*\|\s*(HK\$|£|€|¥|\$)(.*)'
  bid_index: 1
  title_index: 2
  price_index: 4

  extract_estimation_pattern: '(?m)^Estimate\s*\|\s*(HK\$|£|€|¥|\$)\s*(.*)-\s*(HK\$|£|€|¥|\$)(.*)'
  estimation_low_index: 2
  estimation_high_index: 4

  crop_size_and_offset: 1280x120+0+0
  psm: 6